### ISSUE TITLE
加载提示框为什么不能自动消失

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [limxing/Android-PromptDialog#1]
加载提示框应该在规定的时候消失这样体验会比较好，不然一直在那里显示，按返回按钮也没用

**Comment by limxing** [comment]
dissmiss()方法可以关闭

**Comment by zhongzhihuashanghai** [comment]
但是总是需要一个显示时间的吧，
else if (view == loading){
            dialog.showLoading("正在加载中");
            new Thread(){
                @Override
                public void run() {

                    handler.postDelayed(runnable,3000);
                }
            }.start();
        }

然后
Runnable runnable = new Runnable() {
        @Override
        public void run() {
            dialog.dismiss();
        }
    };

我现在是这样做的，这样就能实现自己想要的效果

**Comment by limxing** [comment]
你是说dismisy要停留一下吗

**Comment by zhongzhihuashanghai** [comment]
对呀，比如说要让加载三秒左右，然后让提示框消失，其实这个可以稍微优化下，这只是一个小小的建议

**Comment by limxing** [comment]
可以 谢谢支持

**Comment by zhongzhihuashanghai** [comment]
嗯，做好了可以在那个示例文档里面写一下，写好了能跟我说一下么，我再试试

**Comment by limxing** [comment]
好的，

**Comment by limxing** [comment]
1.0.4可以尝试
 promptDialog = new PromptDialog(this);
promptDialog.getDefaultBuilder().touchAble(true).round(3).loadingDuration(3000);

**Comment by zhongzhihuashanghai** [comment]
试了一下，very nice
