### ISSUE TITLE
关于有些手机动画不执行

### ISSUE THREAD

**Issue by ITzhangyan** [limxing/Android-PromptDialog#4]
我在oppo5.1系统正在登陆动画可以执行，在锤子7.1和华为7.0动画不执行，为什么啊？

**Comment by limxing** [comment]
我也发现了这个问题，是由于Integer.MAX_VALUE 动画循环的方法无效了，所以已经在昨天修改完成了，你试试1.1.2版本，但是我没有测试，祝你好运

**Comment by ITzhangyan** [comment]
恩，就是这个问题，我刚刚看你的源码，也是找到了这个问题，但是我不知道为什么

**Comment by ITzhangyan** [comment]
你可以把100000改成  Animation.INFINITE ，刚刚测试了可以

**Comment by limxing** [comment]
好的 ，感谢
